permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

production_url : http://liuliu.me
title : 静水铭室 Silient Water and Curved Mountain

author :
  name : Liu Liu
  email : i@liuliu.me
  github : liuliu
  twitter : liu_liu
